apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: hotel-management
type: Opaque
stringData:
  # Billing Database
  BILLING_DB_USER: billinguser
  BILLING_DB_PASSWORD: billingpass
  
  # Booking Database
  BOOKING_DB_USER: bookinguser
  BOOKING_DB_PASSWORD: bookingpass
  
  # Customer Database
  CUSTOMER_DB_USER: customeruser
  CUSTOMER_DB_PASSWORD: customerpass
  
  # Room Database
  ROOM_DB_USER: roomuser
  ROOM_DB_PASSWORD: roompass
  
  # RabbitMQ
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin