apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: hotel-management
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  
  # Eureka
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service:8761/eureka/"
  
  # Database URLs - PostgreSQL
  BILLING_DB_URL: "jdbc:postgresql://billing-db:5432/billingdb"
  BOOKING_DB_URL: "jdbc:postgresql://booking-db:5432/bookingdb"
  CUSTOMER_DB_URL: "jdbc:postgresql://customer-db:5432/customerdb"
  ROOM_DB_URL: "jdbc:postgresql://room-db:5432/roomdb"
  
  # RabbitMQ
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  
  # RabbitMQ Exchange & Queues
  RABBITMQ_EXCHANGE_BOOKING: "booking.exchange"
  RABBITMQ_QUEUE_BOOKING_CONFIRMED: "booking.confirmed.queue"
  RABBITMQ_QUEUE_BOOKING_COMPLETED: "booking.completed.queue"
  RABBITMQ_ROUTINGKEY_BOOKING_CONFIRMED: "booking.confirmed"
  RABBITMQ_ROUTINGKEY_BOOKING_COMPLETED: "booking.completed"