apiVersion: v1
kind: Service
metadata:
  name: billing-db
  namespace: hotel-management
spec:
  selector:
    app: billing-db
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: booking-db
  namespace: hotel-management
spec:
  selector:
    app: booking-db
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db
  namespace: hotel-management
spec:
  selector:
    app: customer-db
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: room-db
  namespace: hotel-management
spec:
  selector:
    app: room-db
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None